rpm: fix rpmbuild error
rpmbuild is reporting the following error:

Checking for unpackaged file(s): /usr/lib/rpm/check-files /home/laurent/rpmbuild/BUILDROOT/powerpc-utils-1.3.8-1.ppc64le
error: Installed (but unpackaged) file(s) found:
   /usr/share/man/man8/drmgr.8.gz

This is because the file is not mentioned in the RPM specification file.

Fixes: bd8dd36b33cd ("man: add manpage for the drmgr utility")
Cc: Tyrel Datwyler <tyreld@linux.ibm.com>
Signed-off-by: Laurent Dufour <ldufour@linux.ibm.com>